version: '3'

networks:
    near:

services:

    db:
        image: postgres
        container_name: database_near
        restart: unless-stopped
        environment:
            POSTGRES_USER: "near_user"
            POSTGRES_PASSWORD: "near_password"
            POSTGRES_DB: "near"
        ports:
            - "5432:5432"
        networks:
            - near

    app:
        build:
            context: .
        container_name: api_near
        depends_on:
            - db
        links:
            - db
        ports:
            - "3333:3333"
        networks:
            - near
